name: Backup on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR merge
      if: github.event.pull_request.merged == true
      run: echo "PR was merged."

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure git pull behavior
      run: |
        git config pull.rebase false
        git config pull.ff only
      

    - name: Pull 'Feature/Dev' to 'backup' branch
      run: git pull origin Feature/Dev:backup


